### ISSUE TITLE
希望脚本增加自定义端口功能

### ISSUE THREAD

**Issue by wdssfff00** [TimeRainStarSky/TRSS_AllBot#2]
### 描述

1.容器内端口自定义
例如 [chatgpt-plugin](https://gitee.com/ikechan/chatgpt-plugin) 插件的后台需要容器内开放3321端口
而脚本给的都是固定那几个端口，希望在脚本执行安装时询问下是否开放别的端口

2.容器对外端口固定功能
publish是无脑，但是对于远程的话 容器对外的端口号固定显然更方便，不然每次重启都得重新设定端口（特别是ws反代端口）
解决思路：脚本引导安装时询问是随机分配端口还是挨个自定义对外端口

**Comment by TimeRainStarSky** [comment]
默认设置则没问题，除非修改了容器名则认为是要多开，为了防止冲突所以随机端口，如果要修改端口，建议自行docker run或修改容器配置
