### ISSUE TITLE
安装后启动yunzai提示错误

### ISSUE THREAD

**Issue by TAN-Z-H** [TimeRainStarSky/TRSS_AllBot#4]
![c13e1664f7d825da328c098bb793a4b9](https://github.com/TimeRainStarSky/TRSS_AllBot/assets/70757024/40b64dc7-fc64-43d8-a8a4-8ccedc489f3f)

环境：群晖918+ 7.2up4
如图，用脚本：DIR=/volume3/docker/TRSS_AllBot bash <(curl -L gitee.com/TimeRainStarSky/TRSS_AllBot/raw/main/Install-Docker.sh)
安装后启动提示上述

如果不进行自定义安装位置的话，在进行 #图鉴升级 的命令时则会提示空间不足

**Comment by TimeRainStarSky** [comment]
检查 volume3 文件系统格式和 docker 版本

**Comment by TAN-Z-H** [comment]
> 检查 volume3 文件系统格式和 docker 版本

群晖的应该是Btrfs，docker（Container Manager）为20.10.23-1437

**Comment by TAN-Z-H** [comment]
> 检查 volume3 文件系统格式和 docker 版本

经过查阅资料以及实践，删除安装根目录下/home/tmux-0后再重新安装yunzai可以解决

问题已解决，close
