### ISSUE TITLE
【功能建议】能否新增Napcat

### ISSUE THREAD

**Issue by A1Panda** [TimeRainStarSky/TRSS_AllBot#6]

**Comment by TimeRainStarSky** [comment]
和Lagrange存在功能重复，请给出必须使用NapCat而不是Lagrange的理由

**Comment by A1Panda** [comment]
拉格兰现在风控登陆一段时间就会被踹

**Comment by A1Panda** [comment]
napcat正常

**Comment by TimeRainStarSky** [comment]
https://github.com/LagrangeDev/Lagrange.Core/issues/new/choose

**Comment by A1Panda** [comment]
> https://github.com/LagrangeDev/Lagrange.Core/issues/new/choose

已经跟开发者反馈过该问题开发者表示最近腾讯风控比较厉害
